// Shared graph fixtures for pack-health tests.

import type {
  QuestGraphData,
  QuestNodeData,
  QuestObjectiveData,
  QuestRewardData,
  QuestChapter,
  QuestEdgeData,
  RewardTableData,
} from '../../services/quest-types'

export const makeObjective = (overrides: Partial<QuestObjectiveData>): QuestObjectiveData => ({
  id: 'o',
  label: 'O',
  objective_type: 'item_acquisition',
  target: 'minecraft:dirt',
  target_count: 1,
  required: true,
  item_tag: '',
  nbt_data: '',
  smart_filter: '',
  consume_items: false,
  match_nbt: false,
  ignore_nbt: false,
  exact_match: false,
  task_screen_only: false,
  only_from_crafting: false,
  match_components: false,
  fluid_id: '',
  fluid_amount: 0,
  energy_amount: 0,
  energy_unit: 'FE',
  xp_levels: 0,
  xp_points: 0,
  command: '',
  dimension: '',
  x: 0,
  y: 0,
  z: 0,
  radius: 0,
  box_w: 1,
  box_h: 1,
  box_d: 1,
  ignore_dim: false,
  entity_id: '',
  advancement_id: '',
  custom_json: '',
  description: '',
  stat_name: '',
  stat_value: 0,
  biome_id: '',
  structure_id: '',
  observation_range: 0,
  custom_name: '',
  entity_type_tag: '',
  nbt_filter: '',
  team_stage: false,
  criterion: '',
  ...overrides,
})

export const makeReward = (overrides: Partial<QuestRewardData>): QuestRewardData => ({
  id: 'r',
  label: 'R',
  reward_type: 'item',
  items: [],
  description: '',
  item_id: 'minecraft:diamond',
  item_tag: '',
  item_count: 1, count: 1,
  nbt_data: '',
  smart_filter: '',
  xp_amount: 0,
  xp_levels: 0,
  command: '',
  loot_table: '',
  game_stage: '',
  weight: 1,
  reward_chests: [],
  team_reward: false,
  toast_message: '',
  table_id: '',
  choices: [],
  advancement_id: '',
  random_bonus: 0,
  only_one: false,
  permission_level: 0,
  silent: false,
  feedback_message: '',
  autoclaim: '',
  exclude_from_claim_all: false,
  ignore_reward_blocking: false,
  disable_reward_screen_blur: false,
  ...overrides,
})

export const makeNode = (overrides: Partial<QuestNodeData>): QuestNodeData => ({
  id: 'q',
  node_type: 'quest',
  label: 'Q',
  description: '',
  position: { x: 0, y: 0 },
  data: {},
  objectives: [],
  rewards: [],
  required_items: [],
  chapter_id: null,
  icon: '',
  size: { width: 24, height: 24 },
  color: '',
  visibility: 'normal',
  optional: false,
  silently_complete: false,
  can_be_repeatable: false,
  repeat_cooldown: 0,
  hide_quest_until_deps_complete: false,
  hide_quest_until_quest_complete: false,
  hide_quest_until_all_complete: false,
  disable_reward: false,
  pause_reward: false,
  lock_icon: '',
  hide_lock_icon: false,
  guide_page: '',
  max_completable_dependents: 0,
  subtitle: '',
  quest_background: '',
  shape: '',
  icon_scaling: 1.0,
  tags: [],
  progression_mode: 'default',
  sequential_tasks: false,
  disable_completion_toast: false,
  ignore_reward_blocking: false,
  disable_jei_recipe: false,
  min_window_width: 0,
  hide_details_until_startable: false,
  hide_text_until_completed: false,
  invisible_until_completed: false,
  invisible_until_x_tasks: 0,
  hide_dependency_lines: false,
  hide_dependent_lines: false,
  min_required_dependencies: 0,
  dependency_requirement: 'all_completed',
  ...overrides,
})

export const makeEdge = (id: string, source: string, target: string, edge_type = 'prerequisite'): QuestEdgeData => ({
  id, source, target, label: null, edge_type, inverted: false,
})

export const makeChapter = (overrides: Partial<QuestChapter>): QuestChapter => ({
  id: 'ch',
  title: 'Chapter',
  description: '',
  icon: '',
  background_image: '',
  order_index: 0,
  hide_until_first_quest_complete: false,
  default_quest_size: { width: 24, height: 24 },
  quest_color: '',
  group_id: null,
  default_quest_shape: 'circle',
  default_enabled: true,
  progression_mode: 'default',
  images: [],
  subtitle: '',
  default_min_width: 0,
  always_invisible: false,
  default_hide_dependency_lines: false,
  hide_quest_details_until_startable: false,
  hide_quest_until_deps_visible: false,
  hide_quest_until_deps_complete: false,
  hide_text_until_complete: false,
  autofocus_id: '',
  default_repeatable: false,
  require_sequential_tasks: false,
  ...overrides,
})

export const makeRewardTable = (overrides: Partial<RewardTableData>): RewardTableData => ({
  id: 'rt',
  title: 'Table',
  order_index: 0,
  loot_size: 1,
  empty_weight: 0,
  hide_tooltip: false,
  use_title: false,
  rewards: [],
  ...overrides,
})

export const makeGraph = (overrides: Partial<QuestGraphData>): QuestGraphData => ({
  id: 'graph',
  project_id: 'proj',
  name: 'Pack',
  description: '',
  chapters: [],
  chapter_groups: [],
  reward_tables: [],
  nodes: [],
  edges: [],
  book_progression_mode: 'default',
  book_icon: '',
  book_background_image: '',
  quest_color: '',
  default_quest_size: { width: 24, height: 24 },
  default_quest_shape: 'circle',
  grid_scale: 0.5,
  ...overrides,
})
