// Per-recipe-type `event.*(...)` writers used by `generate_kubejs_scripts`.
// Each arm emits a fixed sequence of `lines.push(...)` calls; content is
// verbatim from the pre-split file (byte-identical generated output).

use super::helpers::ingredient_to_kubejs;

pub(crate) fn generate_kubejs_for_type(recipe_type: &crate::models::RecipeType, recipes: Vec<&crate::models::Recipe>, disabled_ids: &[&String]) -> String {
    let mut lines = vec![
        "// Auto-generated by ModCanvas".to_string(),
        format!("// Recipe type: {:?}", recipe_type).to_lowercase(),
        "".to_string(),
        "ServerEvents.recipes(event => {".to_string(),
        "".to_string(),
    ];
    
    if !disabled_ids.is_empty() {
        lines.push("  // Disabled by ModCanvas".to_string());
        for id in disabled_ids {
            lines.push(format!("  event.remove({{ id: '{id}' }})"));
        }
        lines.push("".to_string());
    }
    
    for recipe in recipes {
        lines.push(format!("  // Recipe: {}", recipe.name));
        
        match recipe_type {
            crate::models::RecipeType::Shaped => {
                if let Some(pattern) = &recipe.pattern {
                    if let Some(key) = &recipe.key {
                        let pattern_str = pattern.iter()
                            .map(|row| format!("\"{}\"", row))
                            .collect::<Vec<_>>()
                            .join(", ");
                        
                        let key_entries: Vec<String> = key.iter()
                            .map(|(k, v)| format!("  {}: {}", k, ingredient_to_kubejs(v)))
                            .collect();
                        
                        lines.push(format!("  event.shaped("));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    [{}],", pattern_str));
                        lines.push(format!("    {{"));
                        for entry in key_entries {
                            lines.push(format!("      {},", entry));
                        }
                        lines.push(format!("    }}"));
                        lines.push(format!("  )"));
                    }
                }
            }
            crate::models::RecipeType::Shapeless => {
                if let Some(ingredients) = &recipe.ingredients {
                    let ing_strs: Vec<String> = ingredients.iter()
                        .map(ingredient_to_kubejs)
                        .collect();
                    
                    lines.push(format!("  event.shapeless("));
                    lines.push(format!("    '{}',", recipe.output.item));
                    lines.push(format!("    [{}],", ing_strs.join(", ")));
                    lines.push(format!("  )"));
                }
            }
            crate::models::RecipeType::Smithing => {
                // Smithing recipes: base + addition -> result
                if let Some(ingredients) = &recipe.ingredients {
                    if ingredients.len() >= 2 {
                        let base = ingredient_to_kubejs(&ingredients[0]);
                        let addition = ingredient_to_kubejs(&ingredients[1]);
                        
                        lines.push(format!("  event.smithing("));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {},", base));
                        lines.push(format!("    {}", addition));
                        lines.push(format!("  )"));
                    }
                }
            }
            crate::models::RecipeType::Stonecutting => {
                if let Some(ingredients) = &recipe.ingredients {
                    if !ingredients.is_empty() {
                        let input = ingredient_to_kubejs(&ingredients[0]);
                        lines.push(format!("  event.stonecutting("));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {}", input));
                        lines.push(format!("  )"));
                    }
                }
            }
            crate::models::RecipeType::Smelting | 
            crate::models::RecipeType::Blasting | 
            crate::models::RecipeType::Smoking | 
            crate::models::RecipeType::Campfire => {
                if let Some(ingredients) = &recipe.ingredients {
                    if !ingredients.is_empty() {
                        let input = ingredient_to_kubejs(&ingredients[0]);
                        let experience = recipe.experience.unwrap_or(0.0);
                        let cooking_time = recipe.cooking_time.unwrap_or(200);
                        
                        let method = match recipe_type {
                            crate::models::RecipeType::Smelting => "smelting",
                            crate::models::RecipeType::Blasting => "blasting",
                            crate::models::RecipeType::Smoking => "smoking",
                            crate::models::RecipeType::Campfire => "campfireCooking",
                            _ => "smelting",
                        };
                        
                        lines.push(format!("  event.{}(", method));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {}", input));
                        let mut close = "  )".to_string();
                        if experience > 0.0 {
                            close.push_str(&format!(".experience({})", experience));
                        }
                        if cooking_time != 200 {
                            close.push_str(&format!(".cookingTime({})", cooking_time));
                        }
                        lines.push(close);
                    }
                }
            }
            _ => {}
        }
        
        lines.push("".to_string());
    }
    
    lines.push("})".to_string());
    lines.join("\n")
}
