//! FTB quest id validity + deterministic re-basing (s42).
//!
//! FTB's `Long.parseLong(s, 16)` THROWS for ids > `Long.MAX_VALUE` (0x7FFF…,
//! verified against the shipped 2101.1.30 jar). On throw the quest registers
//! under a RANDOM id while dependency lookups resolve to 0 and are silently
//! dropped — the "quests visible, no dependency lines" bug. The template and
//! the app's id generator both produced A/B/C-prefixed or top-bit-set ids.
//!
//! Every id the exporter writes must be parseable: positive, not 0/1 (FTB
//! regenerates those too). Invalid ids are re-based DETERMINISTICALLY — the
//! same bad id always maps to the same new id — so export → import → export
//! round-trips are stable and never churn ids.
//!
//! Scope: only FTB-shaped ids (16 hex chars, optional '#') are re-based. The
//! production failure mode — the template's and generator's overflowing
//! 16-hex ids — is entirely FTB-shaped. Non-shaped ids ("q1", "ch_meta")
//! only occur in synthetic/test data and are left untouched.

use std::collections::{HashMap, HashSet};

use crate::quest::*;

/// Does FTB's own id parser accept this id (as a 16-hex long, '#'-prefixed
/// allowed)? 0 and 1 are regenerated by `BaseQuestFile.readID`, so they are
/// invalid too.
pub fn is_valid_ftb_id(id: &str) -> bool {
    let trimmed = id.trim_start_matches('#');
    if trimmed.len() > 16 || trimmed.is_empty() {
        return false;
    }
    match i64::from_str_radix(trimmed, 16) {
        Ok(v) => v != 0 && v != 1,
        Err(_) => false,
    }
}

/// Is this the shape of an FTB id (16 hex chars, optional '#' prefix)?
fn is_ftb_shaped(id: &str) -> bool {
    let trimmed = id.trim_start_matches('#');
    trimmed.len() == 16 && trimmed.chars().all(|c| c.is_ascii_hexdigit())
}

/// FNV-1a 64-bit — deterministic, no external deps, stable across runs.
fn fnv1a64(input: &str) -> u64 {
    let mut hash: u64 = 0xcbf29ce484222325;
    for b in input.as_bytes() {
        hash ^= *b as u64;
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

/// Build the remap: every invalid id in the graph → a deterministic positive
/// replacement that collides with nothing already in `used`.
pub fn build_id_remap(graph: &QuestGraph) -> HashMap<String, String> {
    let mut used: HashSet<String> = HashSet::new();
    let mut remap: HashMap<String, String> = HashMap::new();

    let mut collect = |id: &str, used: &mut HashSet<String>, remap: &mut HashMap<String, String>| {
        if is_valid_ftb_id(id) || !is_ftb_shaped(id) {
            used.insert(id.to_string());
            return;
        }
        if remap.contains_key(id) {
            return;
        }
        // Linear-probe from a stable hash until free, positive, non-0/1.
        let mut candidate = fnv1a64(id) & 0x7fff_ffff_ffff_ffff;
        loop {
            if candidate < 2 {
                candidate = candidate.wrapping_add(1) & 0x7fff_ffff_ffff_ffff;
            }
            let hex = format!("{candidate:016X}");
            if !used.contains(&hex) && !remap.values().any(|v| v == &hex) {
                used.insert(hex.clone());
                remap.insert(id.to_string(), hex);
                return;
            }
            candidate = candidate.wrapping_add(1) & 0x7fff_ffff_ffff_ffff;
        }
    };

    for node in &graph.nodes {
        collect(&node.id, &mut used, &mut remap);
        if let Some(ch) = &node.chapter_id {
            collect(ch, &mut used, &mut remap);
        }
        for o in &node.objectives {
            collect(&o.id, &mut used, &mut remap);
        }
        for r in &node.rewards {
            collect(&r.id, &mut used, &mut remap);
        }
    }
    for e in &graph.edges {
        collect(&e.source, &mut used, &mut remap);
        collect(&e.target, &mut used, &mut remap);
    }
    for c in &graph.chapters {
        collect(&c.id, &mut used, &mut remap);
        if let Some(g) = &c.group_id {
            collect(g, &mut used, &mut remap);
        }
    }
    for g in &graph.chapter_groups {
        collect(&g.id, &mut used, &mut remap);
    }
    for t in &graph.reward_tables {
        collect(&t.id, &mut used, &mut remap);
        for r in &t.rewards {
            collect(&r.id, &mut used, &mut remap);
        }
    }
    remap
}

fn apply<T: Clone>(id: &str, remap: &HashMap<String, String>) -> T
where
    T: From<String>,
{
    remap
        .get(id)
        .cloned()
        .unwrap_or_else(|| id.to_string())
        .into()
}

/// Return a copy of the graph with every invalid id re-based. References
/// (chapter_id, edge source/target, group_id) are remapped consistently, so
/// the exported files are fully self-consistent.
pub fn rebase_invalid_ids(graph: &QuestGraph) -> QuestGraph {
    let remap = build_id_remap(graph);
    if remap.is_empty() {
        return graph.clone();
    }

    let mut g = graph.clone();
    for node in &mut g.nodes {
        node.id = apply(&node.id, &remap);
        node.chapter_id = node.chapter_id.as_ref().map(|c| apply(c, &remap));
        for o in &mut node.objectives {
            o.id = apply(&o.id, &remap);
        }
        for r in &mut node.rewards {
            r.id = apply(&r.id, &remap);
        }
    }
    for e in &mut g.edges {
        e.source = apply(&e.source, &remap);
        e.target = apply(&e.target, &remap);
    }
    for c in &mut g.chapters {
        c.id = apply(&c.id, &remap);
        c.group_id = c.group_id.as_ref().map(|x| apply(x, &remap));
    }
    for grp in &mut g.chapter_groups {
        grp.id = apply(&grp.id, &remap);
    }
    for t in &mut g.reward_tables {
        t.id = apply(&t.id, &remap);
        for r in &mut t.rewards {
            r.id = apply(&r.id, &remap);
        }
    }
    g
}
