//! FTB quest id validity + deterministic re-basing (s42).
//!
//! FTB's `Long.parseLong(s, 16)` THROWS for ids > `Long.MAX_VALUE` (0x7FFF…,
//! verified against the shipped 2101.1.30 jar). On throw the quest registers
//! under a RANDOM id while dependency lookups resolve to 0 and are silently
//! dropped — the "quests visible, no dependency lines" bug. The template and
//! the app's id generator both produced A/B/C-prefixed or top-bit-set ids.
//!
//! Every id the exporter writes must be parseable: positive, not 0/1 (FTB
//! regenerates those too). Invalid ids are re-based DETERMINISTICALLY — the
//! same bad id always maps to the same new id — so export → import → export
//! round-trips are stable and never churn ids.
//!
//! Scope: only FTB-shaped ids (16 hex chars, optional '#') are re-based. The
//! production failure mode — the template's and generator's overflowing
//! 16-hex ids — is entirely FTB-shaped. Non-shaped ids ("q1", "ch_meta")
//! only occur in synthetic/test data and are left untouched.

use std::collections::{HashMap, HashSet};

use crate::quest::*;

/// Does FTB's own id parser accept this id (as a 16-hex long, '#'-prefixed
/// allowed)? 0 and 1 are regenerated by `BaseQuestFile.readID`, so they are
/// invalid too.
pub fn is_valid_ftb_id(id: &str) -> bool {
    let trimmed = id.trim_start_matches('#');
    if trimmed.len() > 16 || trimmed.is_empty() {
        return false;
    }
    match i64::from_str_radix(trimmed, 16) {
        Ok(v) => v != 0 && v != 1,
        Err(_) => false,
    }
}

/// Is this the shape of an FTB id (16 hex chars, optional '#' prefix)?
fn is_ftb_shaped(id: &str) -> bool {
    let trimmed = id.trim_start_matches('#');
    trimmed.len() == 16 && trimmed.chars().all(|c| c.is_ascii_hexdigit())
}

/// FNV-1a 64-bit — deterministic, no external deps, stable across runs.
fn fnv1a64(input: &str) -> u64 {
    let mut hash: u64 = 0xcbf29ce484222325;
    for b in input.as_bytes() {
        hash ^= *b as u64;
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

/// Build the remap: every invalid id in the graph → a deterministic positive
/// replacement that collides with nothing already in `used`.
pub fn build_id_remap(graph: &QuestGraph) -> HashMap<String, String> {
    let mut used: HashSet<String> = HashSet::new();
    let mut remap: HashMap<String, String> = HashMap::new();

    let mut collect = |id: &str, used: &mut HashSet<String>, remap: &mut HashMap<String, String>| {
        if is_valid_ftb_id(id) || !is_ftb_shaped(id) {
            used.insert(id.to_string());
            return;
        }
        if remap.contains_key(id) {
            return;
        }
        // Linear-probe from a stable hash until free, positive, non-0/1.
        let mut candidate = fnv1a64(id) & 0x7fff_ffff_ffff_ffff;
        loop {
            if candidate < 2 {
                candidate = candidate.wrapping_add(1) & 0x7fff_ffff_ffff_ffff;
            }
            let hex = format!("{candidate:016X}");
            if !used.contains(&hex) && !remap.values().any(|v| v == &hex) {
                used.insert(hex.clone());
                remap.insert(id.to_string(), hex);
                return;
            }
            candidate = candidate.wrapping_add(1) & 0x7fff_ffff_ffff_ffff;
        }
    };

    for node in &graph.nodes {
        collect(&node.id, &mut used, &mut remap);
        if let Some(ch) = &node.chapter_id {
            collect(ch, &mut used, &mut remap);
        }
        for o in &node.objectives {
            collect(&o.id, &mut used, &mut remap);
        }
        for r in &node.rewards {
            collect(&r.id, &mut used, &mut remap);
        }
    }
    for e in &graph.edges {
        collect(&e.source, &mut used, &mut remap);
        collect(&e.target, &mut used, &mut remap);
    }
    for c in &graph.chapters {
        collect(&c.id, &mut used, &mut remap);
        if let Some(g) = &c.group_id {
            collect(g, &mut used, &mut remap);
        }
    }
    for g in &graph.chapter_groups {
        collect(&g.id, &mut used, &mut remap);
    }
    for t in &graph.reward_tables {
        collect(&t.id, &mut used, &mut remap);
        for r in &t.rewards {
            collect(&r.id, &mut used, &mut remap);
        }
    }
    remap
}

fn apply<T: Clone>(id: &str, remap: &HashMap<String, String>) -> T
where
    T: From<String>,
{
    remap
        .get(id)
        .cloned()
        .unwrap_or_else(|| id.to_string())
        .into()
}

/// Return a copy of the graph with every invalid id re-based. References
/// (chapter_id, edge source/target, group_id) are remapped consistently, so
/// the exported files are fully self-consistent.
pub fn rebase_invalid_ids(graph: &QuestGraph) -> QuestGraph {
    let remap = build_id_remap(graph);
    if remap.is_empty() {
        return graph.clone();
    }

    let mut g = graph.clone();
    for node in &mut g.nodes {
        node.id = apply(&node.id, &remap);
        node.chapter_id = node.chapter_id.as_ref().map(|c| apply(c, &remap));
        for o in &mut node.objectives {
            o.id = apply(&o.id, &remap);
        }
        for r in &mut node.rewards {
            r.id = apply(&r.id, &remap);
        }
    }
    for e in &mut g.edges {
        e.source = apply(&e.source, &remap);
        e.target = apply(&e.target, &remap);
    }
    for c in &mut g.chapters {
        c.id = apply(&c.id, &remap);
        c.group_id = c.group_id.as_ref().map(|x| apply(x, &remap));
    }
    for grp in &mut g.chapter_groups {
        grp.id = apply(&grp.id, &remap);
    }
    for t in &mut g.reward_tables {
        t.id = apply(&t.id, &remap);
        for r in &mut t.rewards {
            r.id = apply(&r.id, &remap);
        }
    }
    g
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn invalid_ids_are_detected() {
        // 0xA... > Long.MAX_VALUE → FTB's parseLong throws (s42 root cause).
        assert!(!is_valid_ftb_id("A000000000000101"));
        assert!(!is_valid_ftb_id("F5C978FE592C4C5F"));
        assert!(!is_valid_ftb_id("0")); // FTB regenerates 0
        assert!(!is_valid_ftb_id("1")); // and 1
        assert!(!is_valid_ftb_id("not-hex"));
        // Positive ids parse fine.
        assert!(is_valid_ftb_id("310969B8FE0A94DE"));
        assert!(is_valid_ftb_id("1000000000000101"));
        assert!(is_valid_ftb_id("7FFFFFFFFFFFFFFF"));
    }

    #[test]
    fn rebase_is_deterministic_and_consistent() {
    let mut graph = QuestGraph::new("p", "t");
    // One chapter, one quest, one task, one reward, one edge — all with
    // the invalid A/B/C-prefixed ids the template used to ship.
    graph.chapters.push(QuestChapter {
        id: "A000000000000001".into(),
        title: "Early Game".into(),
        description: String::new(),
        icon: String::new(),
        background_image: String::new(),
        order_index: 0,
        hide_until_first_quest_complete: false,
        default_quest_size: QuestSize::default(),
        quest_color: String::new(),
        group_id: None,
        default_quest_shape: QuestShape::Default,
        default_enabled: true,
        progression_mode: QuestProgressionMode::Default,
        images: Vec::new(),
        subtitle: String::new(),
        default_min_width: 0,
        always_invisible: false,
        default_hide_dependency_lines: false,
        hide_quest_details_until_startable: false,
        hide_quest_until_deps_visible: false,
        hide_quest_until_deps_complete: false,
        hide_text_until_complete: false,
        autofocus_id: String::new(),
        default_repeatable: false,
        require_sequential_tasks: false,
    });
        graph.nodes.push(QuestNode {
            id: "A000000000000101".into(),
            node_type: QuestNodeType::Quest,
            label: "Start".into(),
            chapter_id: Some("A000000000000001".into()),
            objectives: vec![QuestObjective {
                id: "B000000000000101".into(),
                ..Default::default()
            }],
            rewards: vec![QuestReward {
                id: "C000000000000101".into(),
                ..Default::default()
            }],
            ..Default::default()
        });
        graph.nodes.push(QuestNode {
            id: "A000000000000102".into(),
            node_type: QuestNodeType::Quest,
            label: "Next".into(),
            chapter_id: Some("A000000000000001".into()),
            ..Default::default()
        });
        graph.edges.push(QuestEdge {
            source: "A000000000000101".into(),
            target: "A000000000000102".into(),
            ..Default::default()
        });
        // A non-FTB-shaped id (synthetic/test data) is out of scope — it
        // must survive the re-base untouched.
        graph.nodes.push(QuestNode {
            id: "q_synthetic".into(),
            node_type: QuestNodeType::Quest,
            label: "Synthetic".into(),
            ..Default::default()
        });

        let a = rebase_invalid_ids(&graph);
        let b = rebase_invalid_ids(&graph);
        // Deterministic: both passes produce the same ids.
        assert_eq!(
            a.nodes.iter().map(|n| n.id.clone()).collect::<Vec<_>>(),
            b.nodes.iter().map(|n| n.id.clone()).collect::<Vec<_>>()
        );
        // Every FTB-shaped id is now valid (the synthetic id is out of scope).
        for n in &a.nodes {
            if n.id == "q_synthetic" {
                continue;
            }
            assert!(is_valid_ftb_id(&n.id), "node id {}", n.id);
            for o in &n.objectives {
                assert!(is_valid_ftb_id(&o.id), "objective id {}", o.id);
            }
            for r in &n.rewards {
                assert!(is_valid_ftb_id(&r.id), "reward id {}", r.id);
            }
        }
        // References stayed consistent: the edge still links the same quests,
        // and the chapter_id still points at the (re-based) chapter.
        let edge = &a.edges[0];
        assert!(a.nodes.iter().any(|n| n.id == edge.source));
        assert!(a.nodes.iter().any(|n| n.id == edge.target));
        let ch = a.nodes[0].chapter_id.as_ref().unwrap();
        assert!(a.chapters.iter().any(|c| &c.id == ch));
        // The synthetic id is out of scope and untouched.
        assert!(a.nodes.iter().any(|n| n.id == "q_synthetic"));
    }

    #[test]
    fn rebased_export_keeps_dependencies() {
        // The s42 regression: a graph with edges + invalid ids must export
        // dependencies that reference the re-based ids — a re-import of the
        // output must rebuild the edges (the editor's dependency lines).
        let tmp = tempfile::tempdir().unwrap();
        let mut graph = QuestGraph::new("p", "t");
        graph.layout = "FlatChapters".into();
        graph.chapters.push(QuestChapter {
            id: "A000000000000001".into(),
            title: "Early Game".into(),
            description: String::new(),
            icon: String::new(),
            background_image: String::new(),
            order_index: 0,
            hide_until_first_quest_complete: false,
            default_quest_size: QuestSize::default(),
            quest_color: String::new(),
            group_id: None,
            default_quest_shape: QuestShape::Default,
            default_enabled: true,
            progression_mode: QuestProgressionMode::Default,
            images: Vec::new(),
            subtitle: String::new(),
            default_min_width: 0,
            always_invisible: false,
            default_hide_dependency_lines: false,
            hide_quest_details_until_startable: false,
            hide_quest_until_deps_visible: false,
            hide_quest_until_deps_complete: false,
            hide_text_until_complete: false,
            autofocus_id: String::new(),
            default_repeatable: false,
            require_sequential_tasks: false,
        });
        graph.nodes.push(QuestNode {
            id: "A000000000000001".into(),
            node_type: QuestNodeType::Chapter,
            label: "Early Game".into(),
            ..Default::default()
        });
        graph.nodes.push(QuestNode {
            id: "A000000000000101".into(),
            node_type: QuestNodeType::Quest,
            label: "Start".into(),
            chapter_id: Some("A000000000000001".into()),
            ..Default::default()
        });
        graph.nodes.push(QuestNode {
            id: "A000000000000102".into(),
            node_type: QuestNodeType::Quest,
            label: "Next".into(),
            chapter_id: Some("A000000000000001".into()),
            ..Default::default()
        });
        graph.edges.push(QuestEdge {
            source: "A000000000000101".into(),
            target: "A000000000000102".into(),
            ..Default::default()
        });

        crate::imports::ftb_quests::export_ftb_quests_snbt_for_layout(&graph, tmp.path(), &Default::default(), None).unwrap();
        let out = tmp.path().join("config").join("ftbquests").join("quests");
        let chapter_file = std::fs::read_dir(out.join("chapters")).unwrap()
            .next().unwrap().unwrap().path();
        let content = std::fs::read_to_string(&chapter_file).unwrap();
        for e in std::fs::read_dir(out.clone()).unwrap().flatten() {
            eprintln!("TREE: quests/{}", e.file_name().to_string_lossy());
            if e.path().is_dir() {
                for f in std::fs::read_dir(e.path()).unwrap().flatten() {
                    eprintln!("  TREE: quests/{}/{}", e.file_name().to_string_lossy(), f.file_name().to_string_lossy());
                }
            }
        }
        eprintln!("EXPORTED CHAPTER:\n{content}");
        assert!(content.contains("dependencies"), "dependencies must survive the re-base:\n{content}");

        // The re-import must rebuild the edge.
        let reimport = crate::imports::ftb_quests::import_ftb_quests(tmp.path()).unwrap();
        eprintln!("REIMPORT: chapters={} quests={} edges={}", reimport.chapter_count, reimport.quest_count, reimport.graph.edges.len());
        assert!(reimport.graph.edges.len() >= 1, "edge must rebuild from the rebased export");
    }
}

#[cfg(test)]
mod real_path_tests {
    use super::*;
    use crate::imports::ftb_quests::import_ftb_quests;

    #[test]
    fn template_graph_keeps_deps_through_rebase_export() {
        // The full realistic path: scaffold the app's own template (FlatChapters,
        // 1/2/3-prefixed ids, dependencies), import it, export with the re-base,
        // and re-import — the edges must survive end to end.
        let tmp = tempfile::tempdir().unwrap();
        crate::templates::scaffold_template(&tmp.path().to_path_buf(), "exploration").unwrap();

        let imported = import_ftb_quests(tmp.path()).unwrap();
        assert!(imported.graph.edges.len() >= 5, "template graph must import with edges, got {}", imported.graph.edges.len());

        let export_dir = tempfile::tempdir().unwrap();
        crate::imports::ftb_quests::export_ftb_quests_snbt_for_layout(&imported.graph, export_dir.path(), &Default::default(), None).unwrap();
        let out = export_dir.path().join("config").join("ftbquests").join("quests");
        for f in std::fs::read_dir(out.join("chapters")).unwrap().flatten() {
            let content = std::fs::read_to_string(f.path()).unwrap();
            assert!(content.contains("dependencies"), "re-based export must keep deps in {}:\n{}", f.path().display(), content);
        }

        let reimport = import_ftb_quests(export_dir.path()).unwrap();
        assert!(reimport.graph.edges.len() >= 5, "edges must survive the rebased export round-trip, got {}", reimport.graph.edges.len());
    }
}
