use std::fs;
use std::path::{Path, PathBuf};
use zip::ZipArchive;

use super::models::TextureEntry;

/// Walk all `.jar` files in `mods_dir`, extract `assets/*/textures/**/*.png`,
/// and index each texture with three normalized key formats:
///
///   Raw key:      `atm:textures/questpics/chap3/creative_star.png`
///   Canonical key:`atm:questpics/chap3/creative_star`
///   Clean key:    `atm:textures/questpics/chap3/creative_star`
///
/// All backslashes are normalized to forward slashes for cross-platform safety.
pub(crate) fn scan_jar_textures_for_registry(jar_path: &Path) -> anyhow::Result<Vec<TextureEntry>> {
    let file = fs::File::open(jar_path)?;
    let mut archive = ZipArchive::new(file)?;
    let mut entries = Vec::new();

    for i in 0..archive.len() {
        let mut entry = match archive.by_index(i) {
            Ok(e) => e,
            Err(_) => continue,
        };

        let raw_name = entry.name().to_string();
        if !raw_name.ends_with(".png") {
            continue;
        }

        let name = raw_name.replace('\\', "/");

        let parts: Vec<&str> = name.split('/').collect();
        if parts.len() < 4 || parts[0] != "assets" {
            continue;
        }

        let namespace = parts[1];
        let textures_prefix = format!("assets/{}/textures/", namespace);
        let rest = &name[textures_prefix.len()..];

        let rest_no_ext = rest.strip_suffix(".png").unwrap_or(rest);
        let raw_key = format!("{}:textures/{}", namespace, rest);
        let canonical_key = format!("{}:{}", namespace, rest_no_ext);
        let clean_key = format!("{}:textures/{}", namespace, rest_no_ext);

        // Store file path for on-demand serving instead of base64
        let file_path = jar_path.to_string_lossy().to_string();
        entries.push(TextureEntry {
            namespace: namespace.to_string(),
            path: name,
            raw_key,
            canonical_key,
            clean_key,
            file_path,
        });
    }

    Ok(entries)
}

/// Scan `kubejs/assets` directory for PNG textures (runtime-generated by KubeJS)
pub fn scan_kubejs_assets(kubejs_assets_dir: &Path) -> anyhow::Result<Vec<TextureEntry>> {
    let mut entries = Vec::new();
    
    fn walk_dir(dir: &Path, namespace: &str, base_dir: &Path, entries: &mut Vec<TextureEntry>) -> anyhow::Result<()> {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_dir() {
                walk_dir(&path, namespace, base_dir, entries)?;
            } else if path.extension().map_or(false, |ext| ext == "png") {
                let rel_path = path.strip_prefix(base_dir)?.to_string_lossy().replace('\\', "/");
                // Strip the leading namespace/textures/ prefix from rel_path since we'll add it back
                let path_without_ns = if rel_path.starts_with(&format!("{}/textures/", namespace)) {
                    rel_path.strip_prefix(&format!("{}/textures/", namespace)).unwrap_or(&rel_path)
                } else {
                    &rel_path
                };
                let rest = path_without_ns.strip_suffix(".png").unwrap_or(path_without_ns);
                
                let raw_key = format!("{}:textures/{}", namespace, path_without_ns);
                let canonical_key = format!("{}:{}", namespace, rest);
                let clean_key = format!("{}:textures/{}", namespace, rest);

                // Store file path for on-demand serving instead of base64
                entries.push(TextureEntry {
                    namespace: namespace.to_string(),
                    path: path_without_ns.to_string(),
                    raw_key,
                    canonical_key,
                    clean_key,
                    file_path: path.to_string_lossy().to_string(),
                });
            }
        }
        Ok(())
    }

    for entry in fs::read_dir(kubejs_assets_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            let namespace = path.file_name().unwrap().to_string_lossy().to_string();
            let textures_dir = path.join("textures");
            if textures_dir.exists() {
                walk_dir(&textures_dir, &namespace, kubejs_assets_dir, &mut entries)?;
            }
        }
    }

    Ok(entries)
}

pub(crate) fn get_jar_meta(path: &Path) -> Option<(u64, u64, String)> {
    let meta = fs::metadata(path).ok()?;
    let size = meta.len();
    let modified = meta
        .modified()
        .ok()
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();
    Some((size, modified, name))
}

/// Collect all `.jar` files in `mods_dir` with their (size, mtime, name)
/// metadata, used for cache validation.
pub(crate) fn collect_jars_with_meta(mods_dir: &Path) -> anyhow::Result<Vec<(PathBuf, u64, u64, String)>> {
    let entries = fs::read_dir(mods_dir)?;
    Ok(entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map_or(false, |ext| ext == "jar"))
        .filter_map(|p| {
            let (size, modified, name) = get_jar_meta(&p)?;
            Some((p, size, modified, name))
        })
        .collect())
}
