use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use zip::ZipArchive;

use rayon::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextureEntry {
    pub namespace: String,
    pub path: String,
    pub raw_key: String,
    pub canonical_key: String,
    pub clean_key: String,
    // Local file path for on-demand texture serving (JAR path or filesystem path)
    pub file_path: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct VirtualAssetRegistry {
    /// Combined lookup map: raw_key, canonical_key, and clean_key all point to the same data_url
    pub by_id: HashMap<String, String>,
    /// All parsed texture entries for introspection
    pub all_textures: Vec<TextureEntry>,
    pub jars_scanned: usize,
    pub textures_indexed: usize,
}

#[derive(Debug, Clone, Serialize)]
pub struct IngestResult {
    pub asset_registry: VirtualAssetRegistry,
    pub jars_scanned: usize,
    pub textures_indexed: usize,
    pub active_instance: String,
}

/// Walk all `.jar` files in `mods_dir`, extract `assets/*/textures/**/*.png`,
/// and index each texture with three normalized key formats:
///
///   Raw key:      `atm:textures/questpics/chap3/creative_star.png`
///   Canonical key:`atm:questpics/chap3/creative_star`
///   Clean key:    `atm:textures/questpics/chap3/creative_star`
///
/// All backslashes are normalized to forward slashes for cross-platform safety.
fn scan_jar_textures_for_registry(jar_path: &Path) -> anyhow::Result<Vec<TextureEntry>> {
    let file = fs::File::open(jar_path)?;
    let mut archive = ZipArchive::new(file)?;
    let mut entries = Vec::new();

    for i in 0..archive.len() {
        let mut entry = match archive.by_index(i) {
            Ok(e) => e,
            Err(_) => continue,
        };

        let raw_name = entry.name().to_string();
        if !raw_name.ends_with(".png") {
            continue;
        }

        let name = raw_name.replace('\\', "/");

        let parts: Vec<&str> = name.split('/').collect();
        if parts.len() < 4 || parts[0] != "assets" {
            continue;
        }

        let namespace = parts[1];
        let textures_prefix = format!("assets/{}/textures/", namespace);
        let rest = &name[textures_prefix.len()..];

        let rest_no_ext = rest.strip_suffix(".png").unwrap_or(rest);
        let raw_key = format!("{}:textures/{}", namespace, rest);
        let canonical_key = format!("{}:{}", namespace, rest_no_ext);
        let clean_key = format!("{}:textures/{}", namespace, rest_no_ext);

        // Store file path for on-demand serving instead of base64
        let file_path = jar_path.to_string_lossy().to_string();
        entries.push(TextureEntry {
            namespace: namespace.to_string(),
            path: name,
            raw_key,
            canonical_key,
            clean_key,
            file_path,
        });
    }

    Ok(entries)
}

/// Scan `kubejs/assets` directory for PNG textures (runtime-generated by KubeJS)
pub fn scan_kubejs_assets(kubejs_assets_dir: &Path) -> anyhow::Result<Vec<TextureEntry>> {
    let mut entries = Vec::new();
    
    fn walk_dir(dir: &Path, namespace: &str, base_dir: &Path, entries: &mut Vec<TextureEntry>) -> anyhow::Result<()> {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_dir() {
                walk_dir(&path, namespace, base_dir, entries)?;
            } else if path.extension().map_or(false, |ext| ext == "png") {
                let rel_path = path.strip_prefix(base_dir)?.to_string_lossy().replace('\\', "/");
                // Strip the leading namespace/textures/ prefix from rel_path since we'll add it back
                let path_without_ns = if rel_path.starts_with(&format!("{}/textures/", namespace)) {
                    rel_path.strip_prefix(&format!("{}/textures/", namespace)).unwrap_or(&rel_path)
                } else {
                    &rel_path
                };
                let rest = path_without_ns.strip_suffix(".png").unwrap_or(path_without_ns);
                
                let raw_key = format!("{}:textures/{}", namespace, path_without_ns);
                let canonical_key = format!("{}:{}", namespace, rest);
                let clean_key = format!("{}:textures/{}", namespace, rest);

                // Store file path for on-demand serving instead of base64
                entries.push(TextureEntry {
                    namespace: namespace.to_string(),
                    path: path_without_ns.to_string(),
                    raw_key,
                    canonical_key,
                    clean_key,
                    file_path: path.to_string_lossy().to_string(),
                });
            }
        }
        Ok(())
    }

    for entry in fs::read_dir(kubejs_assets_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            let namespace = path.file_name().unwrap().to_string_lossy().to_string();
            let textures_dir = path.join("textures");
            if textures_dir.exists() {
                walk_dir(&textures_dir, &namespace, kubejs_assets_dir, &mut entries)?;
            }
        }
    }

    Ok(entries)
}

fn get_jar_meta(path: &Path) -> Option<(u64, u64, String)> {
    let meta = fs::metadata(path).ok()?;
    let size = meta.len();
    let modified = meta
        .modified()
        .ok()
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();
    Some((size, modified, name))
}

/// Cache helpers for `VirtualAssetRegistry`
fn dirs_cache_dir() -> Option<PathBuf> {
    if let Ok(data) = std::env::var("XDG_CACHE_HOME") {
        return Some(PathBuf::from(data).join("modcanvas"));
    }
    if let Ok(home) = std::env::var("HOME") {
        return Some(PathBuf::from(home).join(".cache").join("modcanvas"));
    }
    None
}

fn cache_path(mods_dir: &Path) -> PathBuf {
    let hash = {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};
        let mut h = DefaultHasher::new();
        // Normalize path: canonicalize to remove symlinks, trailing slashes, etc.
        let canonical = fs::canonicalize(mods_dir).unwrap_or_else(|_| mods_dir.to_path_buf());
        let normalized = canonical.to_string_lossy().replace('\\', "/");
        normalized.hash(&mut h);
        format!("{:016x}", h.finish())
    };
    let cache_dir = dirs_cache_dir().unwrap_or_else(|| std::env::temp_dir().join("modcanvas_cache"));
    let _ = fs::create_dir_all(&cache_dir);
    cache_dir.join(format!("ingest_{}.json", hash))
}

/// Ingest an active modpack instance: scan all `.jar` files, build a
/// `VirtualAssetRegistry`, cache the result, and return it along with counts.
pub fn ingest_active_instance(instance_path: &Path) -> IngestResult {
    let act = instance_path.to_string_lossy().to_string();
    let mods_dir = instance_path.join("mods");
    let kubejs_assets_dir = instance_path.join("kubejs").join("assets");
    let _config_dir = instance_path.join("config").join("ftbquests");

    eprintln!("[Ingestion] Starting ingest for: {}", act);
    eprintln!("[Ingestion] mods_dir: {:?}", mods_dir);
    eprintln!("[Ingestion] mods_dir exists: {}", mods_dir.exists());
    eprintln!("[Ingestion] kubejs_assets_dir: {:?}", kubejs_assets_dir);
    eprintln!("[Ingestion] kubejs_assets_dir exists: {}", kubejs_assets_dir.exists());

    if !mods_dir.exists() {
        eprintln!("[Ingestion] No mods directory at {:?}, returning empty registry", mods_dir);
        return IngestResult {
            asset_registry: VirtualAssetRegistry {
                by_id: HashMap::new(),
                all_textures: Vec::new(),
                jars_scanned: 0,
                textures_indexed: 0,
            },
            jars_scanned: 0,
            textures_indexed: 0,
            active_instance: act,
        };
    }

    // Collect jars with metadata for caching
    let current_jars: Vec<(PathBuf, u64, u64, String)> = {
        let entries = match fs::read_dir(&mods_dir) {
            Ok(e) => e,
            Err(_) => {
                return IngestResult {
                    asset_registry: VirtualAssetRegistry {
                        by_id: HashMap::new(),
                        all_textures: Vec::new(),
                        jars_scanned: 0,
                        textures_indexed: 0,
                    },
                    jars_scanned: 0,
                    textures_indexed: 0,
                    active_instance: act,
                };
            }
        };
        entries
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().map_or(false, |ext| ext == "jar"))
            .filter_map(|p| {
                let (size, modified, name) = get_jar_meta(&p)?;
                Some((p, size, modified, name))
            })
            .collect()
    };

    let jars_scanned = current_jars.len();
    eprintln!("[Ingestion] Found {} jar files in {:?}", jars_scanned, mods_dir);

    // Check cache
    const CACHE_VERSION: u32 = 3;
    let cache_hit = {
        let cp = cache_path(&mods_dir);
        if cp.exists() {
            if let Ok(data) = fs::read_to_string(&cp) {
                if let Ok(cached) = serde_json::from_str::<IngestCache>(&data) {
                    if cached.jar_count == jars_scanned && cached.cache_version == CACHE_VERSION {
                        // Check if kubejs/assets have changed
                        let kubejs_mtime = if kubejs_assets_dir.exists() {
                            fs::metadata(&kubejs_assets_dir)
                                .and_then(|m| m.modified())
                                .ok()
                                .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                                .map(|d| d.as_secs())
                        } else {
                            None
                        };
                        // Also count kubejs textures to detect key generation changes
                        let kubejs_texture_count = if kubejs_assets_dir.exists() {
                            scan_kubejs_assets(&kubejs_assets_dir).map(|t| t.len()).unwrap_or(0)
                        } else {
                            0
                        };
                        let kubejs_changed = cached.kubejs_assets_mtime != kubejs_mtime
                            || cached.kubejs_texture_count != kubejs_texture_count;

                        if !kubejs_changed {
                            eprintln!("[Ingestion] Cache hit: {} textures for {}", cached.textures_indexed, &act);
                            let mut by_id: HashMap<String, String> = HashMap::new();
                            for entry in &cached.textures {
                                by_id.insert(entry.raw_key.clone(), entry.file_path.clone());
                                by_id.insert(entry.canonical_key.clone(), entry.file_path.clone());
                                by_id.insert(entry.clean_key.clone(), entry.file_path.clone());
                            }
                            return IngestResult {
                                asset_registry: VirtualAssetRegistry {
                                    by_id,
                                    all_textures: cached.textures.clone(),
                                    jars_scanned,
                                    textures_indexed: cached.textures_indexed,
                                },
                                jars_scanned,
                                textures_indexed: cached.textures_indexed,
                                active_instance: act,
                            };
                        } else {
                            eprintln!("[Ingestion] kubejs/assets changed (mtime or texture count), re-scanning...");
                        }
                    } else if cached.cache_version != CACHE_VERSION {
                        eprintln!("[Ingestion] Cache version mismatch (have {}, need {}), re-scanning...", cached.cache_version, CACHE_VERSION);
                    }
                }
            }
        }
        false
    };

    if !cache_hit {
        eprintln!("[Ingestion] Scanning {} jar files in {:?}...", jars_scanned, mods_dir);
    }

    let scan_results: Vec<Vec<TextureEntry>> = current_jars.par_iter().map(|(jar_path, _, _, _)| {
        scan_jar_textures_for_registry(jar_path).unwrap_or_else(|e| {
            eprintln!("[Ingestion] Failed to scan jar {}: {}", jar_path.display(), e);
            Vec::new()
        })
    }).collect();

    let mut all_textures: Vec<TextureEntry> = Vec::new();
    let mut by_id: HashMap<String, String> = HashMap::new();

    for textures in scan_results {
        for tex in textures {
            // Store file path instead of base64 data URL
            by_id.insert(tex.raw_key.clone(), tex.file_path.clone());
            by_id.insert(tex.canonical_key.clone(), tex.file_path.clone());
            by_id.insert(tex.clean_key.clone(), tex.file_path.clone());
            all_textures.push(tex);
        }
    }

    // Also scan kubejs/assets for runtime-generated textures
    if kubejs_assets_dir.exists() {
        eprintln!("[Ingestion] Scanning kubejs/assets in {:?}...", kubejs_assets_dir);
        if let Ok(kubejs_textures) = scan_kubejs_assets(&kubejs_assets_dir) {
            eprintln!("[Ingestion] Found {} additional textures from kubejs/assets", kubejs_textures.len());
            for tex in kubejs_textures {
                by_id.insert(tex.raw_key.clone(), tex.file_path.clone());
                by_id.insert(tex.canonical_key.clone(), tex.file_path.clone());
                by_id.insert(tex.clean_key.clone(), tex.file_path.clone());
                all_textures.push(tex);
            }
        }
    }

    let textures_indexed = all_textures.len();
    eprintln!("[Ingestion] Indexed {} textures for instance {}", textures_indexed, act);

    // Save cache
    let kubejs_mtime = if kubejs_assets_dir.exists() {
        fs::metadata(&kubejs_assets_dir)
            .and_then(|m| m.modified())
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_secs())
    } else {
        None
    };
    let kubejs_texture_count = if kubejs_assets_dir.exists() {
        scan_kubejs_assets(&kubejs_assets_dir).map(|t| t.len()).unwrap_or(0)
    } else {
        0
    };

    let cache = IngestCache {
        textures: all_textures.clone(),
        textures_indexed,
        jar_count: jars_scanned,
        kubejs_assets_mtime: kubejs_mtime,
        kubejs_texture_count,
        cache_version: CACHE_VERSION,
    };
    let cp = cache_path(&mods_dir);
    if let Ok(data) = serde_json::to_string(&cache) {
        let _ = fs::write(&cp, &data);
        eprintln!("[Ingestion] Cache saved for {}", act);
    }

    IngestResult {
        asset_registry: VirtualAssetRegistry {
            by_id,
            all_textures,
            jars_scanned,
            textures_indexed,
        },
        jars_scanned,
        textures_indexed,
        active_instance: act,
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct IngestCache {
    textures: Vec<TextureEntry>,
    textures_indexed: usize,
    jar_count: usize,
    kubejs_assets_mtime: Option<u64>,
    kubejs_texture_count: usize,
    cache_version: u32,
}

// ── Tauri command ──────────────────────────────────────────────────────────

#[tauri::command]
pub fn ingest_active_instance_cmd(instance_path: String) -> Result<IngestResult, String> {
    let path = std::path::Path::new(&instance_path);
    Ok(ingest_active_instance(path))
}

/// Load the ingest cache for a mods directory if it exists.
fn load_ingest_cache(mods_dir: &Path) -> Option<IngestCache> {
    let cache_path = cache_path(mods_dir);
    if !cache_path.exists() {
        return None;
    }
    let data = fs::read_to_string(&cache_path).ok()?;
    serde_json::from_str::<IngestCache>(&data).ok()
}

/// Extract a texture from its source (JAR archive or filesystem path) and
/// return it as a base64 PNG data URL.
fn texture_data_url_for_entry(entry: &TextureEntry) -> Option<String> {
    if entry.file_path.ends_with(".jar") || entry.file_path.contains(".jar!") {
        let jar_path = Path::new(&entry.file_path);
        let file = fs::File::open(jar_path).ok()?;
        let mut archive = ZipArchive::new(file).ok()?;
        let texture_path = entry.path.replace('\\', "/");
        let mut zip_entry = archive.by_name(&texture_path).ok()?;
        let mut buf = Vec::new();
        zip_entry.read_to_end(&mut buf).ok()?;
        if buf.is_empty() {
            return None;
        }
        Some(format!("data:image/png;base64,{}", STANDARD.encode(&buf)))
    } else {
        let buf = fs::read(&entry.file_path).ok()?;
        if buf.is_empty() {
            return None;
        }
        Some(format!("data:image/png;base64,{}", STANDARD.encode(&buf)))
    }
}

/// Resolve a texture key to a data URL from the ingest cache entries.
fn texture_data_url_for_key(cache: &IngestCache, texture_key: &str) -> Option<String> {
    let entry = cache.textures.iter().find(|t| {
        t.raw_key == texture_key || t.canonical_key == texture_key || t.clean_key == texture_key
    })?;
    texture_data_url_for_entry(entry)
}

/// Fallback: look up a texture key in `kubejs/assets` on the filesystem.
fn fallback_kubejs_texture(texture_key: &str, instance_path: &Path) -> Option<String> {
    let kubejs_assets_dir = instance_path.join("kubejs").join("assets");
    if !kubejs_assets_dir.exists() {
        return None;
    }
    let texture_path = texture_key.replace(':', "/").replace("textures/", "");
    let possible_paths = vec![
        kubejs_assets_dir.join(&texture_path),
        kubejs_assets_dir.join(texture_path.strip_prefix("textures/").unwrap_or(&texture_path)),
    ];

    for path in possible_paths {
        if path.exists() {
            if let Ok(buf) = fs::read(&path) {
                if !buf.is_empty() {
                    return Some(format!("data:image/png;base64,{}", STANDARD.encode(&buf)));
                }
            }
        }
    }
    None
}

/// Serve a texture file on-demand by key.
/// Extracts the texture from the JAR file or reads from filesystem.
#[tauri::command]
pub async fn get_texture_file(texture_key: String, instance_path: String) -> Result<String, String> {
    let instance_path = Path::new(&instance_path);
    if let Some(url) = load_ingest_cache(&instance_path.join("mods"))
        .and_then(|c| texture_data_url_for_key(&c, &texture_key))
    {
        return Ok(url);
    }
    if let Some(url) = fallback_kubejs_texture(&texture_key, instance_path) {
        return Ok(url);
    }
    Err("Texture not found".to_string())
}

/// Batch variant of `get_texture_file`: resolve many texture keys in a single
/// IPC round-trip. Returns a map of key → data URL (or `None` when a texture
/// could not be resolved).
#[tauri::command]
pub async fn get_texture_files(
    texture_keys: Vec<String>,
    instance_path: String,
) -> HashMap<String, Option<String>> {
    let instance_path = Path::new(&instance_path);
    let cache = load_ingest_cache(&instance_path.join("mods"));
    let mut out: HashMap<String, Option<String>> = HashMap::new();
    for key in texture_keys {
        let url = cache
            .as_ref()
            .and_then(|c| texture_data_url_for_key(c, &key))
            .or_else(|| fallback_kubejs_texture(&key, instance_path));
        out.insert(key, url);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::io::Write;
    use std::path::PathBuf;
    use tempfile::tempdir;

    fn create_test_jar(path: &PathBuf, namespace: &str, texture_path: &str) {
        use zip::write::FileOptions;
        use zip::CompressionMethod;
        
        let file = fs::File::create(path).unwrap();
        let mut zip = zip::ZipWriter::new(file);
        
        let full_path = format!("assets/{}/{}", namespace, texture_path);
        let options: FileOptions<'_, ()> = FileOptions::default().compression_method(CompressionMethod::Stored);
        zip.start_file(&full_path, options).unwrap();
        zip.write_all(b"fake_png_data").unwrap();
        
        zip.finish().unwrap();
    }

    fn setup_test_instance() -> tempfile::TempDir {
        let dir = tempdir().unwrap();
        
        let mods_dir = dir.path().join("mods");
        fs::create_dir_all(&mods_dir).unwrap();
        
        create_test_jar(&mods_dir.join("test_mod.jar"), "testmod", "textures/item/test_item.png");
        
        let kubejs_dir = dir.path().join("kubejs").join("assets");
        fs::create_dir_all(kubejs_dir.join("atm").join("textures").join("questpics").join("chap3")).unwrap();
        fs::write(kubejs_dir.join("atm").join("textures").join("questpics").join("chap3").join("creative_star.png"), b"fake_png_data").unwrap();
        
        let quests_dir = dir.path().join("config").join("ftbquests").join("quests");
        fs::create_dir_all(quests_dir.join("lang").join("en_us").join("chapters")).unwrap();
        
        let chapter_content = r#"{
            id: "0123456789abcdef"
            title: "Test Chapter"
            images: [
                { image: "atm:textures/questpics/chap3/creative_star.png" x: 0 y: 0 width: 10 height: 10 }
            ]
        }"#;
        fs::create_dir_all(quests_dir.join("chapters")).unwrap();
        fs::write(quests_dir.join("chapters").join("test_chapter.snbt"), chapter_content).unwrap();
        
        let lang_content = r#"{
            chapter.0123456789abcdef.title: "The ATM Star"
        }"#;
        fs::write(quests_dir.join("lang").join("en_us").join("chapter.snbt"), lang_content).unwrap();
        
        dir
    }

    #[test]
    fn test_scan_kubejs_assets_key_format() {
        let dir = tempdir().unwrap();
        let kubejs_dir = dir.path().join("kubejs").join("assets");
        fs::create_dir_all(kubejs_dir.join("atm").join("textures").join("questpics")).unwrap();
        
        let png_path = kubejs_dir.join("atm").join("textures").join("questpics").join("test_image.png");
        fs::write(&png_path, b"fake_png").unwrap();
        
        let entries = scan_kubejs_assets(&kubejs_dir).unwrap();
        
        assert_eq!(entries.len(), 1);
        let entry = &entries[0];
        
        assert_eq!(entry.namespace, "atm");
        assert_eq!(entry.raw_key, "atm:textures/questpics/test_image.png");
        assert_eq!(entry.canonical_key, "atm:questpics/test_image");
        assert_eq!(entry.clean_key, "atm:textures/questpics/test_image");
        assert!(entry.file_path.ends_with("test_image.png"));
    }

    #[test]
    fn test_scan_kubejs_assets_no_double_namespace() {
        let dir = tempdir().unwrap();
        let kubejs_dir = dir.path().join("kubejs").join("assets");
        fs::create_dir_all(kubejs_dir.join("atm").join("textures").join("questpics")).unwrap();
        fs::write(kubejs_dir.join("atm").join("textures").join("questpics").join("test.png"), b"fake").unwrap();
        
        let entries = scan_kubejs_assets(&kubejs_dir).unwrap();
        
        for entry in &entries {
            assert!(!entry.raw_key.contains("atm:textures/atm/textures"));
            assert!(entry.raw_key.starts_with("atm:textures/"));
        }
    }

    #[test]
    fn test_ingest_cache_version_invalidation() {
        let instance = setup_test_instance();
        
        let result1 = ingest_active_instance(instance.path());
        assert!(result1.textures_indexed > 0);
        
        let result2 = ingest_active_instance(instance.path());
        assert_eq!(result2.textures_indexed, result1.textures_indexed);
        
        // Check cache version
        let cache_files: Vec<_> = fs::read_dir(instance.path().join("mods")).unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().starts_with("ingest_"))
            .collect();
        // Cache is stored in system cache dir, not in instance
    }

    #[test]
    fn test_texture_data_url_for_key_serves_jar_and_kubejs() {
        let instance = setup_test_instance();
        let result = ingest_active_instance(instance.path());
        let mods_dir = instance.path().join("mods");

        let cache = load_ingest_cache(&mods_dir).expect("cache written after ingest");

        // JAR-backed entry resolves to a PNG base64 data URL
        let jar_url = texture_data_url_for_key(&cache, "testmod:item/test_item")
            .expect("jar texture resolves");
        assert!(jar_url.starts_with("data:image/png;base64,"));
        let decoded = STANDARD.decode(jar_url.strip_prefix("data:image/png;base64,").unwrap()).unwrap();
        assert_eq!(decoded, b"fake_png_data");

        // Raw key form resolves too
        assert!(texture_data_url_for_key(&cache, "testmod:textures/item/test_item.png").is_some());
        // Unknown key does not resolve
        assert!(texture_data_url_for_key(&cache, "testmod:item/nope").is_none());

        // KubeJS filesystem-backed entry resolves via canonical key
        let kjs_url = texture_data_url_for_key(&cache, "atm:questpics/chap3/creative_star")
            .expect("kubejs texture resolves");
        assert!(kjs_url.starts_with("data:image/png;base64,"));

        // Batch command resolves the same set through the cache
        assert!(result.textures_indexed >= 2);
    }

    #[test]
    fn test_get_texture_files_batch_resolution() {
        let instance = setup_test_instance();
        let _ = ingest_active_instance(instance.path());

        let out = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(get_texture_files(
                vec![
                    "testmod:textures/item/test_item.png".to_string(),
                    "atm:questpics/chap3/creative_star".to_string(),
                    "testmod:item/missing".to_string(),
                ],
                instance.path().to_string_lossy().to_string(),
            ));

        assert!(out.get("testmod:textures/item/test_item.png").unwrap().is_some());
        assert!(out.get("atm:questpics/chap3/creative_star").unwrap().is_some());
        assert!(out.get("testmod:item/missing").unwrap().is_none());
    }
}
