use std::collections::HashMap;
use std::path::PathBuf;

/// Generate KubeJS recipe scripts from recipes
pub fn generate_kubejs_scripts(
    scripts_dir: &PathBuf,
    recipes: &[crate::models::Recipe],
) -> Vec<(PathBuf, String)> {
    let mut output = Vec::new();
    
    // Group recipes by type for better organization
    let mut by_type: HashMap<crate::models::RecipeType, Vec<&crate::models::Recipe>> = HashMap::new();
    for recipe in recipes {
        by_type.entry(recipe.r#type.clone())
            .or_default()
            .push(recipe);
    }
    
    // Generate one file per recipe type
    for (recipe_type, recipes) in by_type {
        let content = generate_kubejs_for_type(&recipe_type, recipes);
        let filename = format!("recipes-{:?}.js", recipe_type).to_lowercase();
        output.push((scripts_dir.join(filename), content));
    }
    
    output
}

fn generate_kubejs_for_type(recipe_type: &crate::models::RecipeType, recipes: Vec<&crate::models::Recipe>) -> String {
    let mut lines = vec![
        "// Auto-generated by ModCanvas".to_string(),
        format!("// Recipe type: {:?}", recipe_type).to_lowercase(),
        "".to_string(),
        "ServerEvents.recipes(event => {".to_string(),
        "".to_string(),
    ];
    
    for recipe in recipes {
        lines.push(format!("  // Recipe: {}", recipe.name));
        
        match recipe_type {
            crate::models::RecipeType::Shaped => {
                if let Some(pattern) = &recipe.pattern {
                    if let Some(key) = &recipe.key {
                        let pattern_str = pattern.iter()
                            .map(|row| format!("\"{}\"", row))
                            .collect::<Vec<_>>()
                            .join(", ");
                        
                        let key_entries: Vec<String> = key.iter()
                            .map(|(k, v)| format!("  {}: {}", k, ingredient_to_kubejs(v)))
                            .collect();
                        
                        lines.push(format!("  event.shaped("));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    [{}],", pattern_str));
                        lines.push(format!("    {{"));
                        for entry in key_entries {
                            lines.push(format!("      {},", entry));
                        }
                        lines.push(format!("    }}"));
                        lines.push(format!("  )"));
                    }
                }
            }
            crate::models::RecipeType::Shapeless => {
                if let Some(ingredients) = &recipe.ingredients {
                    let ing_strs: Vec<String> = ingredients.iter()
                        .map(ingredient_to_kubejs)
                        .collect();
                    
                    lines.push(format!("  event.shapeless("));
                    lines.push(format!("    '{}',", recipe.output.item));
                    lines.push(format!("    [{}],", ing_strs.join(", ")));
                    lines.push(format!("  )"));
                }
            }
            crate::models::RecipeType::Smithing => {
                // Smithing recipes: base + addition -> result
                if let Some(ingredients) = &recipe.ingredients {
                    if ingredients.len() >= 2 {
                        let base = ingredient_to_kubejs(&ingredients[0]);
                        let addition = ingredient_to_kubejs(&ingredients[1]);
                        
                        lines.push(format!("  event.smithing("));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {},", base));
                        lines.push(format!("    {}", addition));
                        lines.push(format!("  )"));
                    }
                }
            }
            crate::models::RecipeType::Stonecutting => {
                if let Some(ingredients) = &recipe.ingredients {
                    if !ingredients.is_empty() {
                        let input = ingredient_to_kubejs(&ingredients[0]);
                        lines.push(format!("  event.stonecutting("));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {}", input));
                        lines.push(format!("  )"));
                    }
                }
            }
            crate::models::RecipeType::Smelting | 
            crate::models::RecipeType::Blasting | 
            crate::models::RecipeType::Smoking | 
            crate::models::RecipeType::Campfire => {
                if let Some(ingredients) = &recipe.ingredients {
                    if !ingredients.is_empty() {
                        let input = ingredient_to_kubejs(&ingredients[0]);
                        let experience = recipe.experience.unwrap_or(0.0);
                        let cooking_time = recipe.cooking_time.unwrap_or(200);
                        
                        let method = match recipe_type {
                            crate::models::RecipeType::Smelting => "smelting",
                            crate::models::RecipeType::Blasting => "blasting",
                            crate::models::RecipeType::Smoking => "smoking",
                            crate::models::RecipeType::Campfire => "campfireCooking",
                            _ => "smelting",
                        };
                        
                        lines.push(format!("  event.{}(", method));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {}", input));
                        let mut close = "  )".to_string();
                        if experience > 0.0 {
                            close.push_str(&format!(".experience({})", experience));
                        }
                        if cooking_time != 200 {
                            close.push_str(&format!(".cookingTime({})", cooking_time));
                        }
                        lines.push(close);
                    }
                }
            }
            _ => {}
        }
        
        lines.push("".to_string());
    }
    
    lines.push("})".to_string());
    lines.join("\n")
}

fn ingredient_to_kubejs(ing: &crate::models::RecipeIngredient) -> String {
    let mut parts = Vec::new();
    
    if ing.tag.unwrap_or(false) {
        parts.push(format!("#{}", ing.item));
    } else {
        parts.push(format!("'{}'", ing.item));
    }
    
    if let Some(count) = ing.count {
        if count > 1 {
            parts.push(format!("count: {}", count));
        }
    }
    
    if let Some(nbt) = &ing.nbt {
        if !nbt.is_empty() {
            let nbt_str = serde_json::to_string(nbt).unwrap_or_default();
            parts.push(format!("nbt: {}", nbt_str));
        }
    }
    
    if parts.len() == 1 {
        parts[0].clone()
    } else {
        format!("{{ {} }}", parts.join(", "))
    }
}

/// Generate a complete KubeJS startup script with all recipes
pub fn generate_full_startup_script(
    recipes: &[crate::models::Recipe],
    pack_name: &str,
) -> String {
    let mut lines = vec![
        "// ModCanvas Generated KubeJS Startup Script".to_string(),
        format!("// Pack: {}", pack_name),
        "// Generated on: ".to_string() + &chrono::Utc::now().to_rfc3339(),
        "".to_string(),
        "ServerEvents.recipes(event => {".to_string(),
        "".to_string(),
    ];
    
    for recipe in recipes {
        lines.push(format!("  // {}", recipe.name));
        
        match recipe.r#type {
            crate::models::RecipeType::Shaped => {
                if let (Some(pattern), Some(key)) = (&recipe.pattern, &recipe.key) {
                    let pattern_str = pattern.iter()
                        .map(|row| format!("\"{}\"", row))
                        .collect::<Vec<_>>()
                        .join(", ");
                    
                    let key_entries: Vec<String> = key.iter()
                        .map(|(k, v)| format!("  {}: {}", k, ingredient_to_kubejs(v)))
                        .collect();
                    
                    lines.push("  event.shaped(".to_string());
                    lines.push(format!("    '{}',", recipe.output.item));
                    lines.push(format!("    [{}],", pattern_str));
                    lines.push("    {".to_string());
                    for entry in key_entries {
                        lines.push(format!("      {},", entry));
                    }
                    lines.push("    }".to_string());
                    lines.push("  )".to_string());
                }
            }
            crate::models::RecipeType::Shapeless => {
                if let Some(ingredients) = &recipe.ingredients {
                    let ing_strs: Vec<String> = ingredients.iter()
                        .map(ingredient_to_kubejs)
                        .collect();
                    
                    lines.push("  event.shapeless(".to_string());
                    lines.push(format!("    '{}',", recipe.output.item));
                    lines.push(format!("    [{}],", ing_strs.join(", ")));
                    lines.push("  )".to_string());
                }
            }
            crate::models::RecipeType::Smithing => {
                if let Some(ingredients) = &recipe.ingredients {
                    if ingredients.len() >= 2 {
                        let base = ingredient_to_kubejs(&ingredients[0]);
                        let addition = ingredient_to_kubejs(&ingredients[1]);

                        lines.push("  event.smithing(".to_string());
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {},", base));
                        lines.push(format!("    {}", addition));
                        lines.push("  )".to_string());
                    }
                }
            }
            crate::models::RecipeType::Stonecutting => {
                if let Some(ingredients) = &recipe.ingredients {
                    if !ingredients.is_empty() {
                        let input = ingredient_to_kubejs(&ingredients[0]);
                        lines.push("  event.stonecutting(".to_string());
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {}", input));
                        lines.push("  )".to_string());
                    }
                }
            }
            crate::models::RecipeType::Smelting |
            crate::models::RecipeType::Blasting |
            crate::models::RecipeType::Smoking |
            crate::models::RecipeType::Campfire => {
                if let Some(ingredients) = &recipe.ingredients {
                    if !ingredients.is_empty() {
                        let input = ingredient_to_kubejs(&ingredients[0]);
                        let experience = recipe.experience.unwrap_or(0.0);
                        let cooking_time = recipe.cooking_time.unwrap_or(200);

                        let method = match recipe.r#type {
                            crate::models::RecipeType::Smelting => "smelting",
                            crate::models::RecipeType::Blasting => "blasting",
                            crate::models::RecipeType::Smoking => "smoking",
                            crate::models::RecipeType::Campfire => "campfireCooking",
                            _ => "smelting",
                        };

                        lines.push(format!("  event.{}(", method));
                        lines.push(format!("    '{}',", recipe.output.item));
                        lines.push(format!("    {}", input));
                        let mut close = "  )".to_string();
                        if experience > 0.0 {
                            close.push_str(&format!(".experience({})", experience));
                        }
                        if cooking_time != 200 {
                            close.push_str(&format!(".cookingTime({})", cooking_time));
                        }
                        lines.push(close);
                    }
                }
            }
            _ => {}
        }

        lines.push("".to_string());
    }

    lines.push("})".to_string());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{Recipe, RecipeIngredient, RecipeOutput, RecipeType};

    #[test]
    fn test_ingredient_to_kubejs() {
        let ing = RecipeIngredient {
            item: "minecraft:diamond".to_string(),
            count: Some(1),
            tag: Some(false),
            nbt: None,
        };
        assert_eq!(ingredient_to_kubejs(&ing), "'minecraft:diamond'");
        
        let ing_tag = RecipeIngredient {
            item: "forge:ingots/iron".to_string(),
            count: None,
            tag: Some(true),
            nbt: None,
        };
        assert_eq!(ingredient_to_kubejs(&ing_tag), "#forge:ingots/iron");
        
        let ing_count = RecipeIngredient {
            item: "minecraft:diamond".to_string(),
            count: Some(3),
            tag: Some(false),
            nbt: None,
        };
        assert_eq!(ingredient_to_kubejs(&ing_count), "{ 'minecraft:diamond', count: 3 }");
    }

    #[test]
    fn test_generate_shaped_recipe() {
        let recipe = Recipe {
            id: "test".to_string(),
            name: "Test Recipe".to_string(),
            r#type: RecipeType::Shaped,
            group: None,
            pattern: Some(vec!["ABC".to_string(), "DEF".to_string(), "GHI".to_string()]),
            key: Some({
                let mut m = HashMap::new();
                m.insert("A".to_string(), RecipeIngredient { item: "minecraft:diamond".to_string(), count: Some(1), tag: Some(false), nbt: None });
                m.insert("B".to_string(), RecipeIngredient { item: "forge:ingots/iron".to_string(), count: None, tag: Some(true), nbt: None });
                m
            }),
            ingredients: None,
            output: RecipeOutput { item: "minecraft:diamond_sword".to_string(), count: 1, nbt: None },
            experience: None,
            cooking_time: None,
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.shaped"));
        assert!(script.contains("diamond_sword"));
        assert!(script.contains("#forge:ingots/iron"));
    }

    #[test]
    fn test_generate_shapeless_recipe() {
        let recipe = Recipe {
            id: "test_shapeless".to_string(),
            name: "Test Shapeless".to_string(),
            r#type: RecipeType::Shapeless,
            group: None,
            pattern: None,
            key: None,
            ingredients: Some(vec![
                RecipeIngredient { item: "minecraft:iron_ingot".to_string(), count: Some(3), tag: Some(false), nbt: None },
                RecipeIngredient { item: "minecraft:stick".to_string(), count: Some(1), tag: Some(false), nbt: None },
            ]),
            output: RecipeOutput { item: "minecraft:iron_sword".to_string(), count: 1, nbt: None },
            experience: None,
            cooking_time: None,
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.shapeless"));
        assert!(script.contains("iron_sword"));
        assert!(script.contains("iron_ingot"));
    }

    #[test]
    fn test_generate_smithing_recipe() {
        let recipe = Recipe {
            id: "test_smithing".to_string(),
            name: "Test Smithing".to_string(),
            r#type: RecipeType::Smithing,
            group: None,
            pattern: None,
            key: None,
            ingredients: Some(vec![
                RecipeIngredient { item: "minecraft:diamond".to_string(), count: None, tag: Some(false), nbt: None },
                RecipeIngredient { item: "minecraft:stick".to_string(), count: None, tag: Some(false), nbt: None },
            ]),
            output: RecipeOutput { item: "minecraft:diamond_sword".to_string(), count: 1, nbt: None },
            experience: None,
            cooking_time: None,
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.smithing"));
        assert!(script.contains("diamond_sword"));
    }

    #[test]
    fn test_generate_stonecutting_recipe() {
        let recipe = Recipe {
            id: "test_stonecut".to_string(),
            name: "Test Stonecut".to_string(),
            r#type: RecipeType::Stonecutting,
            group: None,
            pattern: None,
            key: None,
            ingredients: Some(vec![
                RecipeIngredient { item: "minecraft:stone".to_string(), count: None, tag: Some(false), nbt: None },
            ]),
            output: RecipeOutput { item: "minecraft:stone_stairs".to_string(), count: 1, nbt: None },
            experience: None,
            cooking_time: None,
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.stonecutting"));
        assert!(script.contains("stone_stairs"));
    }

    #[test]
    fn test_generate_smelting_recipe() {
        let recipe = Recipe {
            id: "test_smelt".to_string(),
            name: "Test Smelt".to_string(),
            r#type: RecipeType::Smelting,
            group: None,
            pattern: None,
            key: None,
            ingredients: Some(vec![
                RecipeIngredient { item: "minecraft:iron_ore".to_string(), count: None, tag: Some(false), nbt: None },
            ]),
            output: RecipeOutput { item: "minecraft:iron_ingot".to_string(), count: 1, nbt: None },
            experience: Some(0.7),
            cooking_time: Some(200),
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.smelting"));
        assert!(script.contains("iron_ingot"));
        assert!(script.contains(".experience(0.7)"));
    }

    #[test]
    fn test_generate_recipe_with_nbt() {
        let mut nbt_map = HashMap::new();
        nbt_map.insert("display".to_string(), serde_json::json!({"Name": "{\"text\":\"Special Diamond\"}"}));

        let recipe = Recipe {
            id: "test_nbt".to_string(),
            name: "Test NBT".to_string(),
            r#type: RecipeType::Shapeless,
            group: None,
            pattern: None,
            key: None,
            ingredients: Some(vec![
                RecipeIngredient {
                    item: "minecraft:diamond".to_string(),
                    count: Some(1),
                    tag: Some(false),
                    nbt: Some(nbt_map),
                },
            ]),
            output: RecipeOutput { item: "minecraft:diamond_block".to_string(), count: 1, nbt: None },
            experience: None,
            cooking_time: None,
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.shapeless"));
        assert!(script.contains("Special Diamond"));
    }

    #[test]
    fn test_generate_empty_recipes() {
        let script = generate_full_startup_script(&[], "Empty Pack");
        assert!(script.contains("ServerEvents.recipes"));
        assert!(script.contains("Empty Pack"));
    }

    #[test]
    fn test_ingredient_with_nbt() {
        let mut nbt_map = HashMap::new();
        nbt_map.insert("Damage".to_string(), serde_json::json!(0));

        let ing = RecipeIngredient {
            item: "minecraft:diamond_sword".to_string(),
            count: Some(1),
            tag: Some(false),
            nbt: Some(nbt_map),
        };
        let result = ingredient_to_kubejs(&ing);
        assert!(result.contains("nbt:"));
        assert!(result.contains("Damage"));
    }

    #[test]
    fn test_generate_multiple_recipes() {
        let recipes = vec![
            Recipe {
                id: "r1".to_string(),
                name: "Shaped".to_string(),
                r#type: RecipeType::Shaped,
                group: None,
                pattern: Some(vec!["A".to_string()]),
                key: Some({
                    let mut m = HashMap::new();
                    m.insert("A".to_string(), RecipeIngredient { item: "minecraft:diamond".to_string(), count: Some(1), tag: Some(false), nbt: None });
                    m
                }),
                ingredients: None,
                output: RecipeOutput { item: "minecraft:diamond_block".to_string(), count: 1, nbt: None },
                experience: None,
                cooking_time: None,
                category: None,
            },
            Recipe {
                id: "r2".to_string(),
                name: "Shapeless".to_string(),
                r#type: RecipeType::Shapeless,
                group: None,
                pattern: None,
                key: None,
                ingredients: Some(vec![
                    RecipeIngredient { item: "minecraft:iron_ingot".to_string(), count: Some(9), tag: Some(false), nbt: None },
                ]),
                output: RecipeOutput { item: "minecraft:iron_block".to_string(), count: 1, nbt: None },
                experience: None,
                cooking_time: None,
                category: None,
            },
        ];

        let script = generate_full_startup_script(&recipes, "Multi Pack");
        assert!(script.contains("diamond_block"));
        assert!(script.contains("iron_block"));
        assert!(script.contains("event.shaped"));
        assert!(script.contains("event.shapeless"));
    }

    #[test]
    fn test_generate_blasting() {
        let recipe = Recipe {
            id: "test_blast".to_string(),
            name: "Test Blast".to_string(),
            r#type: RecipeType::Blasting,
            group: None,
            pattern: None,
            key: None,
            ingredients: Some(vec![
                RecipeIngredient { item: "minecraft:iron_ore".to_string(), count: None, tag: Some(false), nbt: None },
            ]),
            output: RecipeOutput { item: "minecraft:iron_ingot".to_string(), count: 1, nbt: None },
            experience: Some(1.0),
            cooking_time: Some(100),
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.blasting"));
        assert!(script.contains("iron_ingot"));
        assert!(script.contains(".experience(1)"));
        assert!(script.contains(".cookingTime(100)"));
    }

    #[test]
    fn test_generate_smoking() {
        let recipe = Recipe {
            id: "test_smoke".to_string(),
            name: "Test Smoke".to_string(),
            r#type: RecipeType::Smoking,
            group: None,
            pattern: None,
            key: None,
            ingredients: Some(vec![
                RecipeIngredient { item: "minecraft:salmon".to_string(), count: None, tag: Some(false), nbt: None },
            ]),
            output: RecipeOutput { item: "minecraft:cooked_salmon".to_string(), count: 1, nbt: None },
            experience: Some(0.35),
            cooking_time: Some(100),
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.smoking"));
        assert!(script.contains("cooked_salmon"));
        assert!(script.contains(".experience(0.35)"));
    }

    #[test]
    fn test_generate_campfire() {
        let recipe = Recipe {
            id: "test_campfire".to_string(),
            name: "Test Campfire".to_string(),
            r#type: RecipeType::Campfire,
            group: None,
            pattern: None,
            key: None,
            ingredients: Some(vec![
                RecipeIngredient { item: "minecraft:beef".to_string(), count: None, tag: Some(false), nbt: None },
            ]),
            output: RecipeOutput { item: "minecraft:cooked_beef".to_string(), count: 1, nbt: None },
            experience: Some(0.35),
            cooking_time: Some(600),
            category: None,
        };

        let script = generate_full_startup_script(&[recipe], "Test Pack");
        assert!(script.contains("event.campfireCooking"));
        assert!(script.contains("cooked_beef"));
        assert!(script.contains(".cookingTime(600)"));
    }

    #[test]
    fn test_deserialize_camelcase_cooking_time() {
        // The frontend emits `cookingTime` (camelCase); without serde
        // `rename_all = "camelCase"` on Recipe this value would be dropped.
        let json = r#"{
            "id": "r",
            "name": "Smelt",
            "type": "smelting",
            "output": { "item": "minecraft:iron_ingot", "count": 1 },
            "ingredients": [ { "item": "minecraft:iron_ore", "tag": false } ],
            "experience": 0.7,
            "cookingTime": 300
        }"#;
        let recipe: Recipe = serde_json::from_str(json).unwrap();
        assert_eq!(recipe.cooking_time, Some(300));
        assert_eq!(recipe.experience, Some(0.7));
    }
}
